apiVersion: v2
name: spotify-nowplaying
description: A Helm chart for the Spotify Now Playing application
type: application
sources:
  - https://github.com/Soli0222/spotify-nowplaying
version: 3.1.1
appVersion: 4.5.0
